services:
  external-db:
    image: postgres:latest
    container_name: extdb
    environment:
      POSTGRES_DB: ext-services
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6019:5432"
    volumes:
      - ext-db-volm:/var/lib/postgresql/data

volumes:
  ext-db-volm: